export const DefaultPermissions = [
	{ permissionName: 'Dashboard' },
	{ permissionName: 'Employee Cost' },
	{ permissionName: 'Cost Allocations' },
	{ permissionName: 'Journals Entries' },
	{ permissionName: 'Time Activities' },
	{ permissionName: 'TimeLogs' },
	{ permissionName: 'TimeSheets' },
	{ permissionName: 'Settings' },
	{ permissionName: 'Roles' },
	{ permissionName: 'Users' },
	{ permissionName: 'Integrations' },
	{ permissionName: 'Configurations' },
	{ permissionName: 'Subscriptions' },
	{ permissionName: 'Custom Rules' },
	{ permissionName: 'Reports' },
	{ permissionName: 'Time Summary' },
	{ permissionName: 'Payroll Summary' },
	{ permissionName: 'Customer Overview' },
];
